return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"c",
				"cpp",
				"css",
				"lua",
				"python",
				"javascript",
				"typescript",
				"tsx",
				"prisma",
				"zig",
				"go",
				"css",
				"html",
				"vim",
				"bash",
				"markdown",
				"markdown_inline",
				"json",
				"yaml",
				"dockerfile",
				"sql",
				"yaml",
				-- "ghostty",
			},
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
